# Site settings
title: "Liebald Blog"
logo: logo.png # image from https://www.flickr.com/photos/lwr/5496279831/in/set-72157594159055823
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  The blog of Benjamin Liebald
url: "http://liebald.github.io" # the base hostname & protocol for your site
baseurl: "/blog" # the subpath of your site, e.g. /blog/
twitter_username: benjaminliebald
github_username:  liebald

# Build settings
markdown: kramdown
